version: "3"
  
services:
  ddns-schlundtech:
    image: ddns-schlundtech
    container_name: ddns-schlundtech
    restart: "no"
    ports:
      - 8080:8080
    volumes:
      - <path to your config>/ddns-schlundtech.toml:/ddns-schlundtech.toml:ro